### ISSUE TITLE
TLS handshake error: EOF

### ISSUE THREAD

**Issue by oliverhausler** [nats-io/nats.java#273]
Connecting to NATS via TLS frequently fails with Java client.

- Increasing the timeout on both sides to 10s helps to get some more connections.
- Connecting from Windows always succeeds.
- Connecting without TLS always succeeds.
- Connecting using the Node.js library always succeeds.

but

- Connecting from Ubuntu 18.04 fails, with or without conscrypt.

I tried using the conscrypt library. Could somebody quickly check and make sure the problem isn't how I use it:

```
        // URLs are without protocol, prepend tls://
        urls = urls.stream().map(url -> "tls://" + url).collect(Collectors.toSet());

        Provider provider = new OpenSSLProvider();
        Security.insertProviderAt(provider, 1);
        try {
            log.info("Security provider = "+ SSLContext.getDefault().getProvider().getInfo());
        } catch (NoSuchAlgorithmException e) {
            log.error("Accessing security provider failed.", e);
        }

        Options options = new Options.Builder()
                .servers(urls.toArray(new String[0]))
                .userInfo(USERNAME.toCharArray(), PASSWORD.toCharArray())
                .connectionTimeout(Duration.ofMillis(10000))
                .maxReconnects(-1)
                .build();
```

The log returns `Security provider = Android's OpenSSL-backed security provider` so I assume NATS uses conscrypt.

When I connect a listener I see the following errors logged: `Unable to connect to NATS servers: tls://...` and `TLS handshake error: EOF`.

Am I doing something wrong? Then we should improve the README as it doesn't properly say how to do this. Otherwise there's a bug I guess, or TLS on Java 8 is junk.

**Comment by sasbury** [comment]
TLS on Java 8 can be junk, but there are a few things to try....

1. Set `-Djava.security.egd=file:/dev/./urandom` when you run on linux. There is a bug in the other random provider that can cause major startup times. Since TLS is usually early it can often be the first to use the egd. Note, this doesn't effect windows or mac so that is likely the issue.

2. Try setting the traceConnection option and see where the time goes. You are likely right that it is TLS, but worth capturing that if the random fix doesn't work.

3. By default the JDK 8 TLS providers can be slow. I don't recall the specific ones that help but googling may find some recommendations. I did at I found https://github.com/google/conscrypt and https://github.com/wildfly/wildfly-openssl both performed better than the default library. JDK 11, if you can use it, was MUCH better. If you can try with JDK11 and compare it would be a useful data point if #1 doesn't fix the issue.

**Comment by oliverhausler** [comment]
@sasbury Stephen, I'll give feedback along the way, so you have the points we find.

We noticed that you guys are using an elliptic curve algorithm. After switching to conscrypt, we saw this:
```
javax.net.ssl.SSLHandshakeException: Unsupported curve: 1.2.840.10045.3.1.7
at sun.security.ssl.HandshakeMessage$ECDH_ServerKeyExchange.<init>(HandshakeMessage.java:1066)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:284)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
```

It went away after installing the Linux `ca-certificates` package.

**Comment by sasbury** [comment]
Changing the cipher suite is definitely an option, for example TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 appears to do better than TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 because of the Java GCM implementation (i think).

However, the java.security.egd setting, the use of conscrypt and going to JDK 11 are the three biggest boosts we have found.

**Comment by oliverhausler** [comment]
This here talks about your trick 1: https://ruleoftech.com/2016/avoiding-jvm-delays-caused-by-random-number-generation

It doesn't work for us, due to inconsistent read times. As others state, sometimes it takes ms to read the urandom, sometimes it takes minutes. This also seems to be the reason why the connection sometimes works and sometimes does not.

**Comment by oliverhausler** [comment]
@sasbury I am trying to force the client to `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`.

How can I explicitly force a specific cipher suite on the client? I don't seem to have access to the SSLSocket which you create here: https://github.com/nats-io/nats.java/blob/7cbf32c34ebef4876bc85bebec716c2c55e69838/src/main/java/io/nats/client/impl/SocketDataPort.java#L72-L79

**Comment by sasbury** [comment]
i think you disable the ones you don't want with jdk.certpath.disabledAlgorithms

https://www.java.com/en/configure_crypto.html

I haven't done this part, but a user of the library did for testing. I think they ended up using conscrypt instead.

**Comment by oliverhausler** [comment]
I just reverted. If I use conscrypt, my Netty and socket.io server dies after 20mins. :(

_No idea what to do next, I need to think about this for a while. Please leave open and I'll post more as I solve things. Maybe it helps._

**Comment by sasbury** [comment]
I will leave open. There are definitely issues with Java SSL.

Are you able to try JDK 11 just to see if it helps?

**Comment by oliverhausler** [comment]
I must see if other libraries I use are compatible, but I will probably try and let you know.

_May take some time as I need to work on other more urgent stuff first._

**Comment by oliverhausler** [comment]
Sorry, this took a while. We are running on Java 11 now. Same thing:

```
TLS handshake error: EOF
```

**Comment by oliverhausler** [comment]
@sasbury Stephen, I am reading here https://stackoverflow.com/questions/57786439/tls-handshake-error-from-xx-xx-xx-xx14333-eof that `EOF` may mean the client saw unencrypted communication where it tried to establish the `tls://` connection and just cut off unexpectedly.

I am giving NATS only `tls://` URLs, but the server apparently seems to try to communicate with and without TLS on the same port (or the Java client does this). Is it possible it confuses the Java TLS library to see unencrypted stuff and it shuts down?

**Comment by oliverhausler** [comment]
I have found and file the issue. Closing.
https://github.com/nats-io/nats.java/issues/279
