### ISSUE TITLE
What's SID in Message ? Documentation might have a typo

### ISSUE THREAD

**Issue by IsmailMarmoush** [nats-io/nats.java#283]
This [line](https://github.com/nats-io/nats.java/blob/822841dafaa213ef68dd449d6882078c2ad5f59e/src/main/java/io/nats/client/Message.java#L47) has `@return the id associated with the subscription, used in the `  

Also small question, I'm new to Nats, Do messages not have a key* ? 

> `* I understand Nats is different from other technologies like Kafka or Pulsar`

**Comment by kozlovic** [comment]
This is the subscription ID. This ID is generated by the library and sent to the server when the subscription is registered. When the server sends a message to a client connection, it will stamp it with the subscription ID so that the library can dispatch the message to the proper subscription.

> Also small question, I'm new to Nats, Do messages not have a key?

No, messages don't have a header and the payload is a simple byte array that the server does not read or interpret. If you need to have some keys, headers, etc..

**Comment by IsmailMarmoush** [comment]
Thanks @kozlovic
