### ISSUE TITLE
How to monitor the message in and out of topics on the server？

### ISSUE THREAD

**Issue by CaptainTy** [nats-io/nats.java#351]
How to monitor the message in and out of topics on the server？How to confirm that a message sent by a topic is consumed？Is not ack.

**Comment by sasbury** [comment]
for core nats there isn't an acknowledge meant of arrival at the server. This is primarily because the server doesn't hold messages. Instead the receiver(s) should acknowledge the message, either by using a request or including a reply to subject in a publish.

One of the nice things with nats is that the ack can be empty - or can contain the response.

In NATs streaming and JetStream there is a way to get an ACK (see the doc for the appropriate one if that is what you are working on.)
