### ISSUE TITLE
Why not netty for networking?

### ISSUE THREAD

**Issue by yrsh** [nats-io/nats.java#373]
Hi!
Why the current implementation doesn't use netty?

**Comment by ColinSullivan1** [comment]
@sasbury would have insight here..

**Comment by sasbury** [comment]
Someone just ported to NIO, i am not sure that there is any performance benefit. As far as Netty goes I would say it is heavy dependency to add, but someone could build a version that uses that.

**Comment by gytis-ivaskevicius** [comment]
Netty is not only reactive but also has "native transport" implementation, I'm no expert but if I recall correctly it instead of using NIO has some JNI magic that handles networking more directly which results in lower latency. And I'd love to see it implemented as part of this project.

**Comment by sasbury** [comment]
My concern is three fold. First, JNI brings new deployment issues to anyone using the library. Second, since this is a client library and not a server library many of the NIO type optimizations don't actually add much value. The library doesn't open lots of sockets, just the one to the server. Someone just did an NIO re-write, I am curious how it performs in comparison to old socket code. Netty itself brings a big dependency (with possible down stream dependencies).

**Comment by scottf** [comment]
Closing, added will not fix label. sasbury's comments pretty well sums it up, so no need to elaborate.
