### ISSUE TITLE
Why the java sdk  limit the Subject must be in the printable ASCII range? 

### ISSUE THREAD

**Issue by zhishengking** [nats-io/nats.java#937]
I test SDKS for other languages like c 、go  ，they donot have this limit,Can you help me explain why java does this? What do I have to do if I want to get rid of this restriction。

**Comment by zhishengking** [comment]
@scottf  can you help me?

**Comment by sasbury** [comment]
The NATS spec doesn't specify the valid character range, but historically only guaranteed the printable ascii range. The server, written in go, happens to support UTF-8 subject names, but at least a few years ago wasn't written to do UTF8 safe operations on subjects. So, while you could use non-ascii you might get weird results.

The 2.0 version of Nats.Java had a flag for this, i am not sure if the flag is still there, but figured i would comment since I was pretty pushy in getting a clear statement in the specification (although I failed.)

**Comment by scottf** [comment]
@zhishengking We are changing this behavior in the next release of the client. Here is an excerpt from the README that I just added

> For subjects, up until now, the client has been very strict when validating subject names for consumer subject filters and subscriptions.
> It only allowed printable ascii characters except for `*`, `>`, `.`, `\\` and `/`. This restriction has been changed to the following:
> * cannot contain spaces \r \n \t
> * cannot start or end with subject token delimiter .
> * cannot have empty segments
> 
> **This means that UTF characters are now allowed in this client.**
> 
> For queue names, there has been inconsistent validation, if any. Queue names now require the same validation as subjects.
> **Important** We realize this may affect existing applications, but need to require consistency across clients
